version: 2

sources:
  - name: omop
    description: |
      OMOP tables from silver or gold layer depending on the use case.
    catalog: hive_metastore
    schema: omop_source
    tags:
      - source
      - omop
    tables:
      - name: care_site
        columns:
          - name: care_site_id
          - name: care_site_name
          - name: place_of_service_concept_id
          - name: location_id
          - name: care_site_source_value
          - name: place_of_service_source_value
      - name: cdm_source
        columns:
          - name: cdm_source_name
          - name: cdm_source_abbreviation
          - name: cdm_holder
          - name: source_description
          - name: source_documentation_reference
          - name: cdm_etl_reference
          - name: source_release_date
          - name: cdm_release_date
          - name: cdm_version
          - name: cdm_version_concept_id
          - name: vocabulary_version
      - name: cohort
        columns:
          - name: cohort_definition_id
          - name: subject_id
          - name: cohort_start_date
          - name: cohort_end_date
      - name: cohort_definition
        columns:
          - name: cohort_definition_id
          - name: cohort_definition_name
          - name: cohort_definition_description
          - name: definition_type_concept_id
          - name: cohort_definition_syntax
          - name: subject_concept_id
          - name: cohort_initiation_date
      - name: concept
        columns:
          - name: concept_id
          - name: concept_name
          - name: domain_id
          - name: vocabulary_id
          - name: concept_class_id
          - name: standard_concept
          - name: concept_code
          - name: valid_start_date
          - name: valid_end_date
          - name: invalid_reason
      - name: concept_ancestor
        columns:
          - name: ancestor_concept_id
          - name: descendant_concept_id
          - name: min_levels_of_separation
          - name: max_levels_of_separation
      - name: concept_class
        columns:
          - name: concept_class_id
          - name: concept_class_name
          - name: concept_class_concept_id
      - name: concept_relationship
        columns:
          - name: concept_id_1
          - name: concept_id_2
          - name: relationship_id
          - name: valid_start_date
          - name: valid_end_date
          - name: invalid_reason
      - name: concept_synonym
        columns:
          - name: concept_id
          - name: concept_synonym_name
          - name: language_concept_id
      - name: condition_era
        columns:
          - name: condition_era_id
          - name: person_id
          - name: condition_concept_id
          - name: condition_era_start_date
          - name: condition_era_end_date
          - name: condition_occurrence_count
      - name: condition_occurrence
        columns:
          - name: condition_occurrence_id
          - name: person_id
          - name: condition_concept_id
          - name: condition_start_date
          - name: condition_start_datetime
          - name: condition_end_date
          - name: condition_end_datetime
          - name: condition_type_concept_id
          - name: condition_status_concept_id
          - name: stop_reason
          - name: provider_id
          - name: visit_occurrence_id
          - name: visit_detail_id
          - name: condition_source_value
          - name: condition_source_concept_id
          - name: condition_status_source_value
      - name: cost
        columns:
          - name: cost_id
          - name: cost_event_id
          - name: cost_domain_id
          - name: cost_type_concept_id
          - name: currency_concept_id
          - name: total_charge
          - name: total_cost
          - name: total_paid
          - name: paid_by_payer
          - name: paid_by_patient
          - name: paid_patient_copay
          - name: paid_patient_coinsurance
          - name: paid_patient_deductible
          - name: paid_by_primary
          - name: paid_ingredient_cost
          - name: paid_dispensing_fee
          - name: payer_plan_period_id
          - name: amount_allowed
          - name: revenue_code_concept_id
          - name: revenue_code_source_value
          - name: drg_concept_id
          - name: drg_source_value
      - name: death
        columns:
          - name: person_id
          - name: death_date
          - name: death_datetime
          - name: death_type_concept_id
          - name: cause_concept_id
          - name: cause_source_value
          - name: cause_source_concept_id
      - name: device_exposure
        columns:
          - name: device_exposure_id
          - name: person_id
          - name: device_concept_id
          - name: device_exposure_start_date
          - name: device_exposure_start_datetime
          - name: device_exposure_end_date
          - name: device_exposure_end_datetime
          - name: device_type_concept_id
          - name: unique_device_id
          - name: production_id
          - name: quantity
          - name: provider_id
          - name: visit_occurrence_id
          - name: visit_detail_id
          - name: device_source_value
          - name: device_source_concept_id
          - name: unit_concept_id
          - name: unit_source_value
          - name: unit_source_concept_id
      - name: domain
        columns:
          - name: domain_id
          - name: domain_name
          - name: domain_concept_id
      - name: dose_era
        columns:
          - name: dose_era_id
          - name: person_id
          - name: drug_concept_id
          - name: unit_concept_id
          - name: dose_value
          - name: dose_era_start_date
          - name: dose_era_end_date
      - name: drug_era
        columns:
          - name: drug_era_id
          - name: person_id
          - name: drug_concept_id
          - name: drug_era_start_date
          - name: drug_era_end_date
          - name: drug_exposure_count
          - name: gap_days
      - name: drug_exposure
        columns:
          - name: drug_exposure_id
          - name: person_id
          - name: drug_concept_id
          - name: drug_exposure_start_date
          - name: drug_exposure_start_datetime
          - name: drug_exposure_end_date
          - name: drug_exposure_end_datetime
          - name: verbatim_end_date
          - name: drug_type_concept_id
          - name: stop_reason
          - name: refills
          - name: quantity
          - name: days_supply
          - name: sig
          - name: route_concept_id
          - name: lot_number
          - name: provider_id
          - name: visit_occurrence_id
          - name: visit_detail_id
          - name: drug_source_value
          - name: drug_source_concept_id
          - name: route_source_value
          - name: dose_unit_source_value
      - name: drug_strength
        columns:
          - name: drug_concept_id
          - name: ingredient_concept_id
          - name: amount_value
          - name: amount_unit_concept_id
          - name: numerator_value
          - name: numerator_unit_concept_id
          - name: denominator_value
          - name: denominator_unit_concept_id
          - name: box_size
          - name: valid_start_date
          - name: valid_end_date
          - name: invalid_reason
      - name: episode
        columns:
          - name: episode_id
          - name: person_id
          - name: episode_concept_id
          - name: episode_start_date
          - name: episode_start_datetime
          - name: episode_end_date
          - name: episode_end_datetime
          - name: episode_parent_id
          - name: episode_number
          - name: episode_object_concept_id
          - name: episode_type_concept_id
          - name: episode_source_value
          - name: episode_source_concept_id
      - name: episode_event
        columns:
          - name: episode_id
          - name: event_id
          - name: episode_event_field_concept_id
      - name: fact_relationship
        columns:
          - name: domain_concept_id_1
          - name: fact_id_1
          - name: domain_concept_id_2
          - name: fact_id_2
          - name: relationship_concept_id
      - name: location
        columns:
          - name: location_id
          - name: address_1
          - name: address_2
          - name: city
          - name: state
          - name: zip
          - name: county
          - name: location_source_value
          - name: country_concept_id
          - name: country_source_value
          - name: latitude
          - name: longitude
      - name: measurement
        columns:
          - name: measurement_id
          - name: person_id
          - name: measurement_concept_id
          - name: measurement_date
          - name: measurement_datetime
          - name: measurement_time
          - name: measurement_type_concept_id
          - name: operator_concept_id
          - name: value_as_number
          - name: value_as_concept_id
          - name: unit_concept_id
          - name: range_low
          - name: range_high
          - name: provider_id
          - name: visit_occurrence_id
          - name: visit_detail_id
          - name: measurement_source_value
          - name: measurement_source_concept_id
          - name: unit_source_value
          - name: unit_source_concept_id
          - name: value_source_value
          - name: meas_event_field_concept_id
          - name: measurement_event_id
          - name: unique_key
          - name: datasource
          - name: updated_at
      - name: metadata
        columns:
          - name: metadata_id
          - name: metadata_concept_id
          - name: metadata_type_concept_id
          - name: name
          - name: value_as_string
          - name: value_as_concept_id
          - name: value_as_number
          - name: metadata_date
          - name: metadata_datetime
      - name: note
        columns:
          - name: note_id
          - name: person_id
          - name: note_date
          - name: note_datetime
          - name: note_type_concept_id
          - name: note_class_concept_id
          - name: note_title
          - name: note_text
          - name: encoding_concept_id
          - name: language_concept_id
          - name: provider_id
          - name: visit_occurrence_id
          - name: visit_detail_id
          - name: note_source_value
          - name: note_event_id
          - name: note_event_field_concept_id
      - name: note_nlp
        columns:
          - name: note_nlp_id
          - name: note_id
          - name: section_concept_id
          - name: snippet
          - name: offset
          - name: lexical_variant
          - name: note_nlp_concept_id
          - name: note_nlp_source_concept_id
          - name: nlp_system
          - name: nlp_date
          - name: nlp_datetime
          - name: term_exists
          - name: term_temporal
          - name: term_modifiers
      - name: observation
        columns:
          - name: observation_id
          - name: person_id
          - name: observation_concept_id
          - name: observation_date
          - name: observation_datetime
          - name: observation_type_concept_id
          - name: value_as_number
          - name: value_as_string
          - name: value_as_concept_id
          - name: qualifier_concept_id
          - name: unit_concept_id
          - name: provider_id
          - name: visit_occurrence_id
          - name: visit_detail_id
          - name: observation_source_value
          - name: observation_source_concept_id
          - name: unit_source_value
          - name: qualifier_source_value
          - name: value_source_value
          - name: observation_event_id
          - name: obs_event_field_concept_id
          - name: unique_key
          - name: datasource
          - name: updated_at
      - name: observation_period
        columns:
          - name: observation_period_id
          - name: person_id
          - name: observation_period_start_date
          - name: observation_period_end_date
          - name: period_type_concept_id
      - name: payer_plan_period
        columns:
          - name: payer_plan_period_id
          - name: person_id
          - name: payer_plan_period_start_date
          - name: payer_plan_period_end_date
          - name: payer_concept_id
          - name: payer_source_value
          - name: payer_source_concept_id
          - name: plan_concept_id
          - name: plan_source_value
          - name: plan_source_concept_id
          - name: sponsor_concept_id
          - name: sponsor_source_value
          - name: sponsor_source_concept_id
          - name: family_source_value
          - name: stop_reason_concept_id
          - name: stop_reason_source_value
          - name: stop_reason_source_concept_id
      - name: person
        columns:
          - name: person_id
          - name: gender_concept_id
          - name: year_of_birth
          - name: month_of_birth
          - name: day_of_birth
          - name: birth_datetime
          - name: race_concept_id
          - name: ethnicity_concept_id
          - name: location_id
          - name: provider_id
          - name: care_site_id
          - name: person_source_value
          - name: gender_source_value
          - name: gender_source_concept_id
          - name: race_source_value
          - name: race_source_concept_id
          - name: ethnicity_source_value
          - name: ethnicity_source_concept_id
      - name: procedure_occurrence
        columns:
          - name: procedure_occurrence_id
          - name: person_id
          - name: procedure_concept_id
          - name: procedure_date
          - name: procedure_datetime
          - name: procedure_end_date
          - name: procedure_end_datetime
          - name: procedure_type_concept_id
          - name: modifier_concept_id
          - name: quantity
          - name: provider_id
          - name: visit_occurrence_id
          - name: visit_detail_id
          - name: procedure_source_value
          - name: procedure_source_concept_id
          - name: modifier_source_value
      - name: provider
        columns:
          - name: provider_id
          - name: provider_name
          - name: npi
          - name: dea
          - name: specialty_concept_id
          - name: care_site_id
          - name: year_of_birth
          - name: gender_concept_id
          - name: provider_source_value
          - name: specialty_source_value
          - name: specialty_source_concept_id
          - name: gender_source_value
          - name: gender_source_concept_id
      - name: relationship
        columns:
          - name: relationship_id
          - name: relationship_name
          - name: is_hierarchical
          - name: defines_ancestry
          - name: reverse_relationship_id
          - name: relationship_concept_id
      - name: specimen
        columns:
          - name: specimen_id
          - name: person_id
          - name: specimen_concept_id
          - name: specimen_type_concept_id
          - name: specimen_date
          - name: specimen_datetime
          - name: quantity
          - name: unit_concept_id
          - name: anatomic_site_concept_id
          - name: disease_status_concept_id
          - name: specimen_source_id
          - name: specimen_source_value
          - name: unit_source_value
          - name: anatomic_site_source_value
          - name: disease_status_source_value
      - name: visit_detail
        columns:
          - name: visit_detail_id
          - name: person_id
          - name: visit_detail_concept_id
          - name: visit_detail_start_date
          - name: visit_detail_start_datetime
          - name: visit_detail_end_date
          - name: visit_detail_end_datetime
          - name: visit_detail_type_concept_id
          - name: provider_id
          - name: care_site_id
          - name: visit_detail_source_value
          - name: visit_detail_source_concept_id
          - name: admitted_from_concept_id
          - name: admitted_from_source_value
          - name: discharged_to_source_value
          - name: discharged_to_concept_id
          - name: preceding_visit_detail_id
          - name: parent_visit_detail_id
          - name: visit_occurrence_id
      - name: visit_occurrence
        columns:
          - name: visit_occurrence_id
          - name: person_id
          - name: visit_concept_id
          - name: visit_start_date
          - name: visit_start_datetime
          - name: visit_end_date
          - name: visit_end_datetime
          - name: visit_type_concept_id
          - name: provider_id
          - name: care_site_id
          - name: visit_source_value
          - name: visit_source_concept_id
          - name: admitted_from_concept_id
          - name: admitted_from_source_value
          - name: discharged_to_concept_id
          - name: discharged_to_source_value
          - name: preceding_visit_occurrence_id
      - name: vocabulary
        columns:
          - name: vocabulary_id
          - name: vocabulary_name
          - name: vocabulary_reference
          - name: vocabulary_version
          - name: vocabulary_concept_id
